application: rockodevphp
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /static/((css|js)/.*\.(css|js))
  static_files: static/\1
  upload: static/((css|js)/.*\.(css|js))
  expiration: 1s
  secure: always
  #http_headers:
  #  Cache-Control: no-store, no-cache, must-revalidate, max-age=0
  #  Expires: Tue, 03 Jul 2001 06:00:00 GMT
  #  Pragma: no-cache

- url: /static/img/(.*\.(png|jpg|jpeg|gif))
  static_files: static/img/\1
  upload: static/img/(.*\.(png|jpg|jpeg|gif))
  secure: always

#- url: /static/img
#  static_dir: public/img

- url: /polymer
  static_dir: polymer
  secure: always

- url: /chromecast
  static_dir: chromecast
  secure: always

- url: /game/static
  static_dir: game/static
  secure: always

- url: (/game|/game/)
  script: game/index.php
  secure: always

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  secure: always

- url: /disqus\.php
  script: disqus.php
  secure: always

- url: /img\.php
  script: img.php
  secure: always

- url: .*
  script: index.php
  secure: always

#error_handlers:
#  - file: default_error.html
